name: Update Legislative Data

on:
  schedule:
    # Run at 2 AM PST (10 AM UTC) every day
    - cron: '0 10 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main

jobs:
  update-bills:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml
    
    - name: Fetch and update bills data
      run: |
        python scripts/fetch_bills.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-update bills data $(date +'%Y-%m-%d %H:%M')" && git push)